; [mode]
; test = false

; Primary database connection details
[primary_database]
host = localhost
port = 5432
database = primarydb
user = infra
password = infra@123

; Secondary database connection details
[secondary_database]
host = localhost
port = 5434
database = postgres
user = postgres
password = password@123

; Inverter Device - 1 Details
[inverter_1]
device_id = 123          
asset_id = 123            
customer_id = 123           
device_location = TS01      
device_name = INV01            
time_zone = +5:30

; Inverter Device - 2 Details
[inverter_2]
device_id = 123          
asset_id = 123            
customer_id = 123           
device_location = TS01      
device_name = INV02       
time_zone = +5:30         